### ISSUE TITLE
[Suggestion]: Create Diving Helmets and Backtank support.

### ISSUE THREAD

**Issue by MidasMischief** [Fuzss/thinair#1]
### Suggestion (Required)

Hi first off I just wanna say thank yall so much for updating Miners Lung for 1.19.2 with the Thin Air mod, it's one of my favorites for added difficulty to mining. I do have a little suggestion though that would make it a lot better, there was an addon for the 1.18.2 version called Copper Lung which added functionality to Create's diving helmet and copper backtank to activate when in unbreathable areas, I was hoping maybe you could take a look at it and maybe incorporate it into Thin Air as well? Maybe with support for create's netherite diving helmet and backtank as well!

Addon: https://modrinth.com/mod/copper-lungs

**Comment by Feliks-WR** [comment]
Also add support for ad_astra + giselle addon please!

**Comment by Fuzss** [comment]
See https://modrinth.com/mod/create-air-forge and https://modrinth.com/mod/create-air-fabric.
For supporting further modded gear / mods please contact the authors of these mods.

**Comment by SigmaFlame** [comment]
But these mods are only for 1.19.2 and there is no compatibility for Create on 1.20.1.

**Comment by LoSilopante** [comment]
> But these mods are only for 1.19.2 and there is no compatibility for Create on 1.20.1.

My bad, forgot to upload the update on Modrinth too.
