### ISSUE TITLE
[Suggestion]: Configuration options

### ISSUE THREAD

**Issue by Aabaddon** [Fuzss/thinair#10]
### Suggestion (Required)

it would be nice to add the ability to change where the players need oxygen to breathe, like adding modded dimensions to the lack of oxygen

(im trying to build a modpack with the stacked dimensions so players have to dig trhough 2 dimensions before reaching the nether, but i want to make it harder the lower they go)

**Comment by Fuzss** [comment]
Check out the `dimensions` config option, it allows for just that.
