### ISSUE TITLE
[Bug]: respirator not working

### ISSUE THREAD

**Issue by jumble67** [Fuzss/thinair#11]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0

### Notes (Required)

respirator does not effect anything after comparing breath loss with and without it on. tried using all the items in the mod with the respirator on and off multiple times. I love the mod so its a shame.

**Comment by Fuzss** [comment]
Fixed in v4.0.1 and v8.1.0.
