### ISSUE TITLE
[Suggestion]: Height configuration

### ISSUE THREAD

**Issue by rockrevenchy** [Fuzss/thinair#12]
### Suggestion (Required)

hey, I was playing with a setting which allowed higher than normal world Y levels and found myself wanting to change the height settings of thin air to allow high level to be breathable but leave low level unbreathable tho realized its not something I could modify or tweak.

Love the idea of the mod btw!

**Comment by Fuzss** [comment]
Check the `dimensions` entry in the config, specifically the entry for `minecraft:overworld`, it demonstrates you you can define specific air quality ranges.
