### ISSUE TITLE
[Suggestion]: Last version of Thin Air, for Forge 47.1.3

### ISSUE THREAD

**Issue by PickyPixelStudio** [Fuzss/thinair#14]
### Suggestion (Required)

Hey!

We're using Forge 47.1.3, because one of our mod can't get above (forgified fabric API).
If you can and want take a look at it, should be great!

NB : We tried all Fabric's Version, they crash on start. 

PS : We didn't found the 47.1.71 version of Forge on the official site. Can't try it, but we're pretty sure, this will not work, at all xD

Sorry for bother <3

**Comment by Fuzss** [comment]
Thin Air requires Forge 47.2.0 or newer or NeoForge 47.1.71 or newer.
Dowgrading to Forge 47.1.3 is not possible as the mod uses a feature that was introduced in a later version.
The Fabric version works fine if you have the correct version of Puzzles Lib installed.

**Comment by PickyPixelStudio** [comment]
Fabric version with Forgified fabric API?
I'll try it thanks.
