### ISSUE TITLE
[Crash]: 1.20.1

### ISSUE THREAD

**Issue by AMRH2000** [Fuzss/thinair#15]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.1

### Notes (Required)

start game and crash

### Crash Report (Required)

https://gist.github.com/AMRH2000/bc6b0b75e132f977fd4478495653e01b

**Comment by Fuzss** [comment]
Please report this to Sniffer Plus, the crash is caused on their end.
