### ISSUE TITLE
[Suggestion]: About Chinese Translation

### ISSUE THREAD

**Issue by kazukokawagawa** [Fuzss/thinair#2]
### Suggestion (Required)

[This article uses Machine translation. Sorry for the unclear expression.]

Hello author of this mod! I know you have written a mod called Thin Air, but due to the lack of an open source project for this mod on Github and the unique nature of the network in China, I am unable to chat happily with you on Twitter. I deeply apologize.

**I will write a Chinese translated JSON for Thin Air**. May I ask if the author agrees to include this JSON in the updated version of Minecraft Forge 1.19.2 of this mod? (I think I will synchronize and update it on the updated version.)

Thanks!

**Comment by Fuzss** [comment]
If you provide a translation file I‘ll be happy to include that.

**Comment by kazukokawagawa** [comment]
I'm doing it now!
![image](https://github.com/Fuzss/thinair/assets/109492503/ae8cb7ae-b26b-4652-a601-19d9c431dff4)
And....thanks again!

**Comment by kazukokawagawa** [comment]
I'm done! Here is where the file was downloaded:
[Download it!](https://kazukokawagawa.github.io/Webpan/ThinAir-v4.0.0-1.19.2-Forge.jar)
My Chinese file is in ThinAir-v4.0.0-1.19.2-Forge.jar/assets/thinair/lang/zh_cn.json
Now Chinese time is 21 pm, good night! Feel free to leave me a message on GitHub. If the localization is not in place, welcome to correct.

**Comment by Fuzss** [comment]
Thanks! Has been added in v8.1.0.
