### ISSUE TITLE
[Bug]: The endurance of respirator can drop below 0.

### ISSUE THREAD

**Issue by 4Daster4** [Fuzss/thinair#22]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

ThinAir-v8.1.3-1.20.1-Forge

### Notes (Required)

The endurance of respirator can drop below 0 instead of being destroyed in survival mode after the endurance of the respirator is exhausted.
![BUG](https://github.com/Fuzss/thinair/assets/125967673/2f8c2684-db8e-4181-8803-2b1776abbbff)

**Comment by Fuzss** [comment]
Thanks, fixed in v8.1.4.

**Comment by tatjam** [comment]
Hey! Any chance of getting a fix for the Steampunk modpack (Minecraft ver. 1.19.2)? It's currently running thinair version 4.0.1, and the bug is also happening there.

**Comment by Darkvulpine** [comment]
bug still present in 1.19.2.
