### ISSUE TITLE
[Suggestion]: Introduce tag for equipment to work at different air qualities

### ISSUE THREAD

**Issue by TraipsingShadow** [Fuzss/thinair#24]
### Suggestion (Required)

Right now, the existing tag `breathing_equipment` found at `tags/items/breathing_equipment.json` is only for breathing at "Yellow" air levels.

It would be a nice addition if we could have tags for different air qualities, say, for "Red" air.

An additional suggestion regarding this would be to change how `breathing_equipment` is structured. My suggestion would be this:

```JSON
{
  "values": [
    {
      "item": "thinair:respirator",
      "effectivity": {
        "red_air": {
          "isEffective": false,
          "damage": 10
          "damageToPlayer": 10
        },
        "yellow_air": {
          "isEffective": true,
          "damage": 1
          "damageToPlayer": 0
        }
      }
    }
  ]
}
```

`isEffective` determines if the item is effective at that air level.
`damage` determines the amount of damage the item receives at that air level per the mod's default per tick/time interval setting.
`damageToPlayer` determines the damage given to the player if worn at that level. Best way to think of this is breathing in the "wrong" kind of air at that level (like scuba diving or mountain climbing where the air is *thin*!).

The additional suggestion is not important. Even just the tags for red air equipment would be enough!

**Comment by Fuzss** [comment]
Added `thinair:heavy_breathing_utility` which is empty by default for protection from red air.
I don't see the need to provide too many customization options beyond that honestly, hardly anyone will use those.
