### ISSUE TITLE
[Bug]: Air Bubbles Flickering Into and Out of Appearance Rather than Depleting Air

### ISSUE THREAD

**Issue by CraftyZombie** [Fuzss/thinair#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.3

### Notes (Required)

The air bubbles on the HUD simply flash on and off, never depleting and causing extreme annoyance.

Steps to Reproduce:
1. Be in an area with limited air.

(Note: My debug.log is also included in the gist that contains my latest.log.)

### latest.log (Optional)

https://gist.github.com/CraftyZombie/1c6e0e940c1c3e9b9d02e025d77f2cdd

**Comment by Fuzss** [comment]
Are you playing multiplayer?

**Comment by CraftyZombie** [comment]
No.

**Comment by CraftyZombie** [comment]
This is no longer the case. Sorry for the lack of information!
