### ISSUE TITLE
[Suggestion]: A config option that changes alwaysBreathingEntities to a blacklist from a whitelist

### ISSUE THREAD

**Issue by Inpaladin** [Fuzss/thinair#3]
Title.  Having to manually enter every modded mob that spawns in the nether, end, and overworld(for ones that only spawn in deep caves or tall mountains) is not ideal for making modpacks.  
Additionally, having mobs suffocate in the overworld at all essentially just means there are no mobs in the areas where oxygen applies, which I personally do not like.  I do appreciate having mob suffocation as an option for pack creators though.

That being said, love the concept for the mod.  Being able to add a more natural technology barrier to certain areas in packs is wonderful.

**Comment by Aabaddon** [comment]
there should be a way so only players suffocate and not any other entity

**Comment by Fuzss** [comment]
This is now a tag in v8.1.0 (`thinair:air_quality_sensitive`) and only includes the entities that should be affected by breathing.
By default this includes all humanoid mobs (players, villagers, illagers).
