### ISSUE TITLE
[Suggestion]: Thin Air doesn't currently play nice with Ad Astra's oxygen loader.

### ISSUE THREAD

**Issue by VCheesey** [Fuzss/thinair#33]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.19.2

### Mod Version(s) (Optional)

v4.0.1

### Suggestion (Required)

Description
The Thin Air mod causes you to (invariably?) suffocate at high altitudes, even when you have an oxygen distributor setup from the Ad Astra mod providing air to the sealed room you're in.

Reproduction Steps

1. Install both Ad Astra and Thin Air. (I use the SteamPunk modpack on CurseForge, for reference.)
2. Build a sealed room above Y=128 in the overworld, with a volume of less than 3000 blocks.
3. Create an running Ad Astra oxygen distributor setup for that room.
4. Right click on the oxygen distributor block once the setup is running and set it to show the oxygen in the room.
5. Be in the room without any oxygen-providing gear equipped to your player.
6. Notice that you still suffocate even though Ad Astra's oxygen loader is providing breathable air to the room.

**Comment by Fuzss** [comment]
Ad Astra is not supported, for adding mod specific support look into this: https://modrinth.com/mod/create-air-fabric
If there is anything missing from that mod please contact the author, I'm not interested in providing mod support.
