### ISSUE TITLE
[Suggestion]: Compatibility with Immersive Portals and more

### ISSUE THREAD

**Issue by Nerimazeth** [Fuzss/thinair#5]
### Suggestion (Required)

I would appreciate adding compatibility so that the portal block of Immersive Portals generates the green air bubble in the Nether. It would also be helpful to have a green bubble for the End portal and its Immersive Portals counterpart. An configuration file to add other blocks to the bubble generation would be appreciated for modified environments.

**Comment by Fuzss** [comment]
Air quality provider blocks are now controlled via block tags. You yourself can now add Immersive Portals' blocks to the `thinair:green_air_providers` block tag for them to be supported. If you share the corresponding block ids here I can add them to the mod by default.
