### ISSUE TITLE
[Crash]: Original Miner's Lung mod crashes occasionally, may transfer over to this mod

### ISSUE THREAD

**Issue by squoshi** [Fuzss/thinair#7]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

0.2.2

### Notes (Required)

Sit in the game for a while at proper depth and sometimes a crash can occur.

### Crash Report (Required)

https://gist.github.com/squoshi/13a61db0d886c83af1cdf03786af0ef6

**Comment by Fuzss** [comment]
Should be fixed in v8.1.0 by making involved collection synchronized.
