### ISSUE TITLE
[Crash]: Crash during start-up

### ISSUE THREAD

**Issue by OscarHdez103** [Fuzss/thinair#9]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

I just load the game with Forge - 47.1.43. I only have this mod and puzzles lib in the mod folder. The crash doesn't load the game and gives me exit code: 1. Since there is no crash report file I will upload into there all of the game output

### Crash Report (Required)

https://pastebin.com/iu4vyDg1

### latest.log (Optional)

https://pastebin.com/gXYPEWpC

**Comment by Fuzss** [comment]
Forge had an update which broke a mixin in the mod. Fixed in v8.1.0.
